package org.corp.sro.domain;
// Generated 02-ago-2013 21:51:03 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="sro"
)
public class Paciente  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPaciente;
     private String histClinica="";
     private String nombres="";
     private String apellidos="";
     private int edad;
     private Date fechNac;
     private boolean eliminacion=true;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Paciente() {
    }
    
	public Paciente(String histClinica, boolean eliminacion){
		this.histClinica = histClinica;
		this.eliminacion = eliminacion;
	}
    public Paciente(String histClinica, String nombres, String apellidos, int edad, Date fechNac, boolean eliminacion) {
        this.histClinica = histClinica;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.edad = edad;
        this.fechNac = fechNac;
        this.eliminacion = eliminacion;
    }
    public Paciente(String histClinica, String nombres, String apellidos, int edad, Date fechNac, boolean eliminacion, Set<Reserva> reservas) {
       this.histClinica = histClinica;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.edad = edad;
       this.fechNac = fechNac;
       this.eliminacion = eliminacion;
       this.reservas = reservas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPaciente", unique=true, nullable=false)
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="HistClinica", unique=true, length=30)
    public String getHistClinica() {
        return this.histClinica;
    }
    
    public void setHistClinica(String histClinica) {
        this.histClinica = histClinica;
    }

    
    @Column(name="Nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="Apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="Edad")
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechNac", length=10)
    public Date getFechNac() {
        return this.fechNac;
    }
    
    public void setFechNac(Date fechNac) {
        this.fechNac = fechNac;
    }

    
    @Column(name="Eliminacion", nullable=false)
    public boolean isEliminacion() {
        return this.eliminacion;
    }
    
    public void setEliminacion(boolean eliminacion) {
        this.eliminacion = eliminacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Paciente paciente = (Paciente) o;

        if (idPaciente != null ? idPaciente.equals(paciente.idPaciente) : paciente.idPaciente != null)
            return false;

        return true;
    }
}


